### ISSUE TITLE
AttributeError: 'ExceptHandler' object has no attribute 'depth'

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#112]
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/sobolev/Documents/PyCharmProjects/rostelecom_svetochka/.venv/lib/python3.6/site-packages/flake8/checker.py", line 648, in _run_checks
    return checker.run_checks()
  File "/Users/sobolev/Documents/PyCharmProjects/rostelecom_svetochka/.venv/lib/python3.6/site-packages/flake8/checker.py", line 579, in run_checks
    self.run_ast_checks()
  File "/Users/sobolev/Documents/PyCharmProjects/rostelecom_svetochka/.venv/lib/python3.6/site-packages/flake8/checker.py", line 486, in run_ast_checks
    checker = self.run_check(plugin, tree=ast)
  File "/Users/sobolev/Documents/PyCharmProjects/rostelecom_svetochka/.venv/lib/python3.6/site-packages/flake8/checker.py", line 435, in run_check
    return plugin['plugin'](**arguments)
  File "/Users/sobolev/Documents/PyCharmProjects/rostelecom_svetochka/.venv/lib/python3.6/site-packages/flake8/plugins/pyflakes.py", line 91, in __init__
    withDoctest=with_doctest)
  File "/Users/sobolev/Documents/PyCharmProjects/rostelecom_svetochka/.venv/lib/python3.6/site-packages/pyflakes/checker.py", line 495, in __init__
    self.runDeferred(self._deferredFunctions)
  File "/Users/sobolev/Documents/PyCharmProjects/rostelecom_svetochka/.venv/lib/python3.6/site-packages/pyflakes/checker.py", line 532, in runDeferred
    handler()
  File "/Users/sobolev/Documents/PyCharmProjects/rostelecom_svetochka/.venv/lib/python3.6/site-packages/pyflakes/checker.py", line 1172, in runFunction
    self.handleNode(stmt, node)
  File "/Users/sobolev/Documents/PyCharmProjects/rostelecom_svetochka/.venv/lib/python3.6/site-packages/pyflakes/checker.py", line 863, in handleNode
    handler(node)
  File "/Users/sobolev/Documents/PyCharmProjects/rostelecom_svetochka/.venv/lib/python3.6/site-packages/pyflakes/checker.py", line 1310, in TRY
    self.handleNode(child, node)
  File "/Users/sobolev/Documents/PyCharmProjects/rostelecom_svetochka/.venv/lib/python3.6/site-packages/pyflakes/checker.py", line 863, in handleNode
    handler(node)
  File "/Users/sobolev/Documents/PyCharmProjects/rostelecom_svetochka/.venv/lib/python3.6/site-packages/pyflakes/checker.py", line 816, in handleChildren
    self.handleNode(node, tree)
  File "/Users/sobolev/Documents/PyCharmProjects/rostelecom_svetochka/.venv/lib/python3.6/site-packages/pyflakes/checker.py", line 863, in handleNode
    handler(node)
  File "/Users/sobolev/Documents/PyCharmProjects/rostelecom_svetochka/.venv/lib/python3.6/site-packages/pyflakes/checker.py", line 816, in handleChildren
    self.handleNode(node, tree)
  File "/Users/sobolev/Documents/PyCharmProjects/rostelecom_svetochka/.venv/lib/python3.6/site-packages/pyflakes/checker.py", line 863, in handleNode
    handler(node)
  File "/Users/sobolev/Documents/PyCharmProjects/rostelecom_svetochka/.venv/lib/python3.6/site-packages/pyflakes/checker.py", line 1048, in NAME
    self.handleNodeStore(node)
  File "/Users/sobolev/Documents/PyCharmProjects/rostelecom_svetochka/.venv/lib/python3.6/site-packages/pyflakes/checker.py", line 782, in handleNodeStore
    self.addBinding(node, binding)
  File "/Users/sobolev/Documents/PyCharmProjects/rostelecom_svetochka/.venv/lib/python3.6/site-packages/pyflakes/checker.py", line 665, in addBinding
    if existing and not self.differentForks(node, existing.source):
  File "/Users/sobolev/Documents/PyCharmProjects/rostelecom_svetochka/.venv/lib/python3.6/site-packages/pyflakes/checker.py", line 647, in differentForks
    if self.descendantOf(lnode, items, ancestor) ^ \
  File "/Users/sobolev/Documents/PyCharmProjects/rostelecom_svetochka/.venv/lib/python3.6/site-packages/pyflakes/checker.py", line 637, in descendantOf
    if self.getCommonAncestor(node, a, stop):
  File "/Users/sobolev/Documents/PyCharmProjects/rostelecom_svetochka/.venv/lib/python3.6/site-packages/pyflakes/checker.py", line 629, in getCommonAncestor
    if (lnode.depth > rnode.depth):
AttributeError: 'ExceptHandler' object has no attribute 'depth'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sobolev/Documents/PyCharmProjects/rostelecom_svetochka/.venv/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/Users/sobolev/Documents/PyCharmProjects/rostelecom_svetochka/.venv/lib/python3.6/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/Users/sobolev/Documents/PyCharmProjects/rostelecom_svetochka/.venv/lib/python3.6/site-packages/flake8/main/application.py", line 396, in run
    self._run(argv)
  File "/Users/sobolev/Documents/PyCharmProjects/rostelecom_svetochka/.venv/lib/python3.6/site-packages/flake8/main/application.py", line 384, in _run
    self.run_checks()
  File "/Users/sobolev/Documents/PyCharmProjects/rostelecom_svetochka/.venv/lib/python3.6/site-packages/flake8/main/application.py", line 310, in run_checks
    self.file_checker_manager.run()
  File "/Users/sobolev/Documents/PyCharmProjects/rostelecom_svetochka/.venv/lib/python3.6/site-packages/flake8/checker.py", line 319, in run
    self.run_parallel()
  File "/Users/sobolev/Documents/PyCharmProjects/rostelecom_svetochka/.venv/lib/python3.6/site-packages/flake8/checker.py", line 288, in run_parallel
    for ret in pool_map:
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
AttributeError: 'ExceptHandler' object has no attribute 'depth'
```

**Comment by sobolevn** [comment]
Regression test:

```python
# -*- coding: utf-8 -*-

from server.logics.exceptions import AuthenticationException
from server.models import ApplicationUser, TelegramSession


def current_session(
    telegram_id: int,
    for_update: bool = True,
) -> TelegramSession:
    """
    Was triggering `AttributeError`.

    See: https://github.com/wemake-services/wemake-python-styleguide/issues/112
    """
    try:
        query = TelegramSession.objects.all()
        if for_update:  # Try to comment this `if` to fix everything
            query = query.select_for_update()

        return query.get(
            uid=telegram_id,
            is_verified=True,
        )

    except TelegramSession.DoesNotExist:
        raise AuthenticationException('Session is missing')
```

**Comment by b0g3r** [comment]
Same issue with `python 3.6.5 `and `wemake-python-styleguide 0.6.0` 🤔

**Comment by sobolevn** [comment]
@b0g3r can you please provide versions of `pyflakes` and `pycodestyle` in your virtualenv?
I guess that it happens because of the old versions. It should be:

```
pycodestyle==2.4.0
pyflakes==2.0.0
```

**Comment by sobolevn** [comment]
Yes, this is an issue indeed. This happens because of the `.parent` property mismatch for my plugin and `pyflakes`.

I will publish `0.6.1` asap.

**Comment by b0g3r** [comment]
I have a new issue with 0.6.1 🎉 

See traceback: https://gist.github.com/b0g3r/0dd39a58adad1f82c5bf0031a27f8131

**Comment by sobolevn** [comment]
@b0g3r can you please create a new issue for this case? 
I will need some code sample to reproduce this issue.
