### ISSUE TITLE
AttributeError: 'Checker' object has no attribute 'options'

### ISSUE THREAD

**Issue by RandyRomero** [wemake-services/wemake-python-styleguide#1414]
# Bug report

Hello. I see it's a known problem - https://github.com/wemake-services/wemake-python-styleguide/issues/937

Using wemake-python-styleguide on Python 3.8.1 installed via pyenv seems impossible due to this error:

Traceback (most recent call last):
  File "/Users/mikheevaia/.pyenv/versions/3.8.1/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/mikheevaia/.pyenv/versions/3.8.1/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Users/mikheevaia/Library/Caches/pypoetry/virtualenvs/auth-zuoKRAM--py3.8/lib/python3.8/site-packages/flake8/checker.py", line 666, in _run_checks
    return checker.run_checks()
  File "/Users/mikheevaia/Library/Caches/pypoetry/virtualenvs/auth-zuoKRAM--py3.8/lib/python3.8/site-packages/flakehell/_patched/_checkers.py", line 167, in run_checks
    super().run_checks()
  File "/Users/mikheevaia/Library/Caches/pypoetry/virtualenvs/auth-zuoKRAM--py3.8/lib/python3.8/site-packages/flake8/checker.py", line 598, in run_checks
    self.run_ast_checks()
  File "/Users/mikheevaia/Library/Caches/pypoetry/virtualenvs/auth-zuoKRAM--py3.8/lib/python3.8/site-packages/flake8/checker.py", line 502, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "/Users/mikheevaia/Library/Caches/pypoetry/virtualenvs/auth-zuoKRAM--py3.8/lib/python3.8/site-packages/wemake_python_styleguide/checker.py", line 153, in run
    visitor = visitor_class.from_checker(self)
  File "/Users/mikheevaia/Library/Caches/pypoetry/virtualenvs/auth-zuoKRAM--py3.8/lib/python3.8/site-packages/wemake_python_styleguide/visitors/base.py", line 114, in from_checker
    return cls(options=checker.options, filename=checker.filename)
AttributeError: 'Checker' object has no attribute 'options'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mikheevaia/Library/Caches/pypoetry/virtualenvs/auth-zuoKRAM--py3.8/bin/flakehell", line 10, in <module>
    sys.exit(entrypoint())
  File "/Users/mikheevaia/Library/Caches/pypoetry/virtualenvs/auth-zuoKRAM--py3.8/lib/python3.8/site-packages/flakehell/_cli.py", line 39, in entrypoint
    exit_code, msg = main(argv)
  File "/Users/mikheevaia/Library/Caches/pypoetry/virtualenvs/auth-zuoKRAM--py3.8/lib/python3.8/site-packages/flakehell/_cli.py", line 31, in main
    return COMMANDS[command_name](argv=argv[1:])
  File "/Users/mikheevaia/Library/Caches/pypoetry/virtualenvs/auth-zuoKRAM--py3.8/lib/python3.8/site-packages/flakehell/commands/_lint.py", line 11, in lint_command
    app.run(argv)
  File "/Users/mikheevaia/Library/Caches/pypoetry/virtualenvs/auth-zuoKRAM--py3.8/lib/python3.8/site-packages/flake8/main/application.py", line 393, in run
    self._run(argv)
  File "/Users/mikheevaia/Library/Caches/pypoetry/virtualenvs/auth-zuoKRAM--py3.8/lib/python3.8/site-packages/flake8/main/application.py", line 381, in _run
    self.run_checks()
  File "/Users/mikheevaia/Library/Caches/pypoetry/virtualenvs/auth-zuoKRAM--py3.8/lib/python3.8/site-packages/flake8/main/application.py", line 300, in run_checks
    self.file_checker_manager.run()
  File "/Users/mikheevaia/Library/Caches/pypoetry/virtualenvs/auth-zuoKRAM--py3.8/lib/python3.8/site-packages/flake8/checker.py", line 329, in run
    self.run_parallel()
  File "/Users/mikheevaia/Library/Caches/pypoetry/virtualenvs/auth-zuoKRAM--py3.8/lib/python3.8/site-packages/flake8/checker.py", line 293, in run_parallel
    for ret in pool_map:
  File "/Users/mikheevaia/.pyenv/versions/3.8.1/lib/python3.8/multiprocessing/pool.py", line 448, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/Users/mikheevaia/.pyenv/versions/3.8.1/lib/python3.8/multiprocessing/pool.py", line 865, in next
    raise value
AttributeError: 'Checker' object has no attribute 'options'

## System information
I get this bug on macOS Mojave 10.14.4

On Linux Mint 19.1 (5.6.3-050603-generic) everything works well though. 

### flake8 information

Contents of `flake8 --bug-report`:
```
{
  "dependencies": [
    {
      "dependency": "entrypoints",
      "version": "0.3"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.8.1",
    "system": "Darwin"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "flake8-annotations-complexity",
      "version": "0.0.2"
    },
    {
      "is_local": false,
      "plugin": "flake8-bandit",
      "version": "2.1.2"
    },
    {
      "is_local": false,
      "plugin": "flake8-blind-except",
      "version": "0.1.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-broken-line",
      "version": "0.1.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-bugbear",
      "version": "19.8.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-comprehensions",
      "version": "3.2.2"
    },
    {
      "is_local": false,
      "plugin": "flake8-darglint",
      "version": "1.3.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-debugger",
      "version": "3.2.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-docstrings",
      "version": "1.5.0, pydocstyle: 5.0.2"
    },
    {
      "is_local": false,
      "plugin": "flake8-eradicate",
      "version": "0.2.4"
    },
    {
      "is_local": false,
      "plugin": "flake8-executable",
      "version": "2.0.3"
    },
    {
      "is_local": false,
      "plugin": "flake8-print",
      "version": "3.1.4"
    },
    {
      "is_local": false,
      "plugin": "flake8-return",
      "version": "0.1.3"
    },
    {
      "is_local": false,
      "plugin": "flake8-string-format",
      "version": "0.2.3"
    },
    {
      "is_local": false,
      "plugin": "flake8_builtins",
      "version": "1.5.2"
    },
    {
      "is_local": false,
      "plugin": "flake8_coding",
      "version": "1.3.2"
    },
    {
      "is_local": false,
      "plugin": "flake8_commas",
      "version": "2.0.0"
    },
    {
      "is_local": false,
      "plugin": "flake8_isort",
      "version": "2.9.1"
    },
    {
      "is_local": false,
      "plugin": "flake8_pep3101",
      "version": "1.2.1"
    },
    {
      "is_local": false,
      "plugin": "flake8_quotes",
      "version": "2.1.2"
    },
    {
      "is_local": false,
      "plugin": "logging-format",
      "version": "0.6.0"
    },
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "naming",
      "version": "0.9.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.5.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.1.1"
    },
    {
      "is_local": false,
      "plugin": "pylint",
      "version": "2.5.2"
    },
    {
      "is_local": false,
      "plugin": "radon",
      "version": "2.4.0"
    },
    {
      "is_local": false,
      "plugin": "rst-docstrings",
      "version": "0.0.11"
    },
    {
      "is_local": false,
      "plugin": "wemake-python-styleguide",
      "version": "0.13.0"
    }
  ],
  "version": "3.7.8"
}
```

### pip information

Contents of `pip freeze`:
add-trailing-comma==1.5.0
aio-pika==6.6.0
aiohttp==3.6.2
aiohttp-apispec==2.2.1
aiohttp-devtools==0.13.1
aioredis==1.3.1
aiormq==3.2.2
apipkg==1.5
apispec==3.3.0
appdirs==1.4.4
astor==0.8.1
astroid==2.4.1
async-timeout==3.0.1
asyncpg==0.20.1
asynctest==0.13.0
attrs==19.3.0
bandit==1.6.2
black==19.10b0
certifi==2020.4.5.1
chardet==3.0.4
click==7.1.2
cognitive-complexity==0.0.4
colorama==0.3.9
coverage==5.1
darglint==1.3.0
ddtrace==0.37.1
devtools==0.5.1
docutils==0.16
dparse==0.5.1
entrypoints==0.3
eradicate==1.0
execnet==1.7.1
flake8==3.7.8
flake8-annotations-complexity==0.0.2
flake8-bandit==2.1.2
flake8-blind-except==0.1.1
flake8-broken-line==0.1.1
flake8-bugbear==19.8.0
flake8-builtins==1.5.3
flake8-coding==1.3.2
flake8-commas==2.0.0
flake8-comprehensions==3.2.2
flake8-debugger==3.2.1
flake8-docstrings==1.5.0
flake8-eradicate==0.2.4
flake8-executable==2.0.3
flake8-isort==2.9.1
flake8-logging-format==0.6.0
flake8-pep3101==1.3.0
flake8-plugin-utils==1.3.0
flake8-polyfill==1.0.2
flake8-print==3.1.4
flake8-pytest-style==0.1.3
flake8-quotes==2.1.2
flake8-rst-docstrings==0.0.11
flake8-string-format==0.2.3
flakehell==0.3.1
gitdb==4.0.5
GitPython==3.1.2
hiredis==1.0.1
idna==2.9
iniherit==0.3.9
intervaltree==3.0.2
isort==4.3.15
Jinja2==2.11.2
lazy-object-proxy==1.4.3
mando==0.6.4
MarkupSafe==1.1.1
marshmallow==3.2.1
matchlib==0.2.1
mccabe==0.6.1
more-itertools==8.3.0
msgpack==1.0.0
multidict==4.7.6
mypy==0.761
mypy-extensions==0.4.3
packaging==20.4
pamqp==2.3.0
pathspec==0.8.0
pbr==5.4.5
pep8-naming==0.9.1
phonenumbers==8.10.18
pluggy==0.13.1
prometheus-async==19.2.0
prometheus-client==0.7.1
protobuf==3.11.3
psycopg2-binary==2.8.4
py==1.8.1
pycodestyle==2.5.0
pydantic==1.1
pydocstyle==5.0.2
pyflakes==2.1.1
Pygments==2.6.1
PyJWT==1.7.1
pylint==2.5.2
pyparsing==2.4.7
pytest==5.4.2
pytest-aiohttp==0.3.0
pytest-cov==2.7.1
pytest-deadfixtures==2.2.0
pytest-forked==1.1.3
pytest-mock==1.10.4
pytest-picked==0.4.1
pytest-randomly==3.1.0
pytest-xdist==1.30.0
pytz==2019.1
PyYAML==4.2b4
radon==2.4.0
regex==2020.5.14
requests==2.23.0
restructuredtext-lint==1.3.0
safety==1.8.5
sentry-sdk==0.13.0
simplejson==3.17.0
six==1.14.0
smmap==3.0.4
snowballstemmer==2.0.0
sortedcontainers==2.1.0
stevedore==1.32.0
structlog==19.1.0
termcolor==1.1.0
testfixtures==6.14.1
text-unidecode==1.3
tokenize-rt==4.0.0
toml==0.10.1
typed-ast==1.4.1
typing-extensions==3.7.4.1
ujson==1.35
urllib3==1.25.9
uvloop==0.14.0
watchgod==0.6
wcwidth==0.1.9
webargs==5.5.3
wemake-python-styleguide==0.13.0
wrapt==1.12.1
xenon==0.5.5
yarl==1.4.2
yoyo-migrations==6.1.0

**Comment by RandyRomero** [comment]
I got rid of this bug by updating flake8 from 3.7.8 to 3.8.2 and flakehell at least to 0.3.4.
