### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'parent'

### ISSUE THREAD

**Issue by antlu** [wemake-services/wemake-python-styleguide#1480]
# Bug report

## What's wrong

When running the linter, I get this error:

```
flake8.checker            ForkPoolWorker-8   1912 CRITICAL Plugin F raised an unexpected exception
Traceback (most recent call last):
  File ".../lib/python3.6/site-packages/flake8/checker.py", line 435, in run_check
    return plugin["plugin"](**arguments)
  File ".../lib/python3.6/site-packages/flake8/plugins/pyflakes.py", line 94, in __init__
    file_tokens=file_tokens,
  File ".../lib/python3.6/site-packages/pyflakes/checker.py", line 673, in __init__
    self.runDeferred(self._deferredFunctions)
  File ".../lib/python3.6/site-packages/pyflakes/checker.py", line 710, in runDeferred
    handler()
  File ".../lib/python3.6/site-packages/pyflakes/checker.py", line 1418, in <lambda>
    self.deferFunction(lambda: self.handleDoctests(node))
  File ".../lib/python3.6/site-packages/pyflakes/checker.py", line 1156, in handleDoctests
    self.addBinding(None, Builtin('_'))
  File ".../lib/python3.6/site-packages/pyflakes/checker.py", line 878, in addBinding
    parent_stmt = self.getParent(value.source)
  File ".../lib/python3.6/site-packages/pyflakes/checker.py", line 816, in getParent
    node = node.parent
AttributeError: 'NoneType' object has no attribute 'parent'
```

### What causes the error

The `_` alias, as in `from django.utils.translation import gettext_lazy as _`
The error doesn't appear with other aliases. Moreover, even `_` works as an alias in other modules, but not in [a specific one](https://github.com/Hexlet/hexlet-friends/blob/0cc2b943f6c3ad961361de5ae1cecc44fb287870/contributors/utils/misc.py#L10).

## How is that should be

No errors occur. 🙂 

### flake8 information

Contents of `flake8 --bug-report`:
```
{
  "dependencies": [
    {
      "dependency": "entrypoints",
      "version": "0.3"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.6.9",
    "system": "Linux"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "flake8-bandit",
      "version": "2.1.2"
    },
    {
      "is_local": false,
      "plugin": "flake8-broken-line",
      "version": "0.2.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-bugbear",
      "version": "19.8.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-comprehensions",
      "version": "3.2.2"
    },
    {
      "is_local": false,
      "plugin": "flake8-darglint",
      "version": "0.4.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-debugger",
      "version": "3.2.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-docstrings",
      "version": "1.5.0, pydocstyle: 5.0.2"
    },
    {
      "is_local": false,
      "plugin": "flake8-eradicate",
      "version": "0.3.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-string-format",
      "version": "0.2.3"
    },
    {
      "is_local": false,
      "plugin": "flake8_commas",
      "version": "2.0.0"
    },
    {
      "is_local": false,
      "plugin": "flake8_isort",
      "version": "2.9.1"
    },
    {
      "is_local": false,
      "plugin": "flake8_quotes",
      "version": "2.1.2"
    },
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "naming",
      "version": "0.9.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.5.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.1.1"
    },
    {
      "is_local": false,
      "plugin": "rst-docstrings",
      "version": "0.0.12"
    },
    {
      "is_local": false,
      "plugin": "wemake_python_styleguide",
      "version": "0.14.0"
    }
  ],
  "version": "3.7.9"
}
```

### pip information

Contents of `pip freeze`:
```
APScheduler==3.6.3
asgiref==3.2.7
astor==0.8.1
attrs==19.3.0
bandit==1.6.2
certifi==2019.11.28
chardet==3.0.4
colorama==0.3.9
darglint==1.2.0
dj-database-url==0.5.0
Django==3.0.7
django-crispy-forms==1.9.1
docutils==0.16
entrypoints==0.3
eradicate==1.0
Faker==4.1.0
flake8==3.7.9
flake8-bandit==2.1.2
flake8-broken-line==0.2.0
flake8-bugbear==19.8.0
flake8-commas==2.0.0
flake8-comprehensions==3.2.2
flake8-debugger==3.2.1
flake8-docstrings==1.5.0
flake8-eradicate==0.3.0
flake8-isort==2.9.1
flake8-polyfill==1.0.2
flake8-quotes==2.1.2
flake8-rst-docstrings==0.0.12
flake8-string-format==0.2.3
gitdb==4.0.2
GitPython==3.1.0
gunicorn==20.0.4
idna==2.9
importlib-metadata==1.6.0
isort==4.3.21
mccabe==0.6.1
more-itertools==8.0.2
pbr==5.4.4
pep8-naming==0.9.1
psycopg2==2.8.5
psycopg2-binary==2.8.4
pycodestyle==2.5.0
pydocstyle==5.0.2
pyflakes==2.1.1
Pygments==2.6.1
python-dateutil==2.8.1
python-dotenv==0.13.0
pytz==2019.3
PyYAML==5.3.1
requests==2.23.0
restructuredtext-lint==1.3.0
six==1.14.0
smmap==3.0.1
snowballstemmer==2.0.0
sqlparse==0.3.1
stevedore==1.32.0
testfixtures==6.14.0
text-unidecode==1.3
toml==0.10.0
typing-extensions==3.7.4.2
tzlocal==2.0.0
urllib3==1.25.8
wemake-python-styleguide==0.14.0
whitenoise==5.1.0
zipp==3.1.0
```

**Comment by sobolevn** [comment]
Looks like `pyflakes` issue. Can you please post the same issue there?

**Comment by antlu** [comment]
Okay.
I thought about that, but running `pyflakes file.py` produces no error. 🤷‍♂️

**Comment by sobolevn** [comment]
Can you verify it like this:

```python
rm -rf venv
python3 -m venv venv
source venv/bin/activate
pip install flake8
flake8 your_file.py
```

?

**Comment by antlu** [comment]
No errors.

**Comment by sobolevn** [comment]
So, we can now add plugins one by one to find which one has this problem. The last one should be `wps` itself. The others order is not important.

My guess is that some other plugin adds `.parent` attribute and breaks stuff. 😞

**Comment by antlu** [comment]
I've reinstalled the package. Works well now. 😊
