### ISSUE TITLE
New version of isort broke flake8-isort module

### ISSUE THREAD

**Issue by dyens** [wemake-services/wemake-python-styleguide#1512]
# Bug report

## What's wrong

After updating packages have a bug in flake8-isort module.
Or you can get this error in new environment.

```> poetry run flake8
ERROR:flake8.plugins.manager:cannot import name 'SortImports' from 'isort' (/home/dyens/.cache/pypoetry/virtualenvs/ttt-LUnx8CLc-py3.7/lib64/python3.7/site-packages/isort/__init__.py)
Traceback (most recent call last):
  File "/home/dyens/.cache/pypoetry/virtualenvs/ttt-LUnx8CLc-py3.7/lib64/python3.7/site-packages/flake8/plugins/manager.py", line 157, in load_plugin
    self._load()
  File "/home/dyens/.cache/pypoetry/virtualenvs/ttt-LUnx8CLc-py3.7/lib64/python3.7/site-packages/flake8/plugins/manager.py", line 134, in _load
    self._plugin = self.entry_point.load()
  File "/home/dyens/.cache/pypoetry/virtualenvs/ttt-LUnx8CLc-py3.7/lib64/python3.7/site-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/dyens/.cache/pypoetry/virtualenvs/ttt-LUnx8CLc-py3.7/lib64/python3.7/site-packages/flake8_isort.py", line 3, in <module>
    from isort import SortImports
ImportError: cannot import name 'SortImports' from 'isort' (/home/dyens/.cache/pypoetry/virtualenvs/ttt-LUnx8CLc-py3.7/lib64/python3.7/site-packages/isort/__init__.py)
CRITICAL:flake8.plugins.manager:Flake8 failed to load plugin "I00" due to cannot import name 'SortImports' from 'isort' (/home/dyens/.cache/pypoetry/virtualenvs/ttt-LUnx8CLc-py3.7/lib64/python3.7/site-packages/isort/__init__.py).
Traceback (most recent call last):
  File "/home/dyens/.cache/pypoetry/virtualenvs/ttt-LUnx8CLc-py3.7/lib64/python3.7/site-packages/flake8/plugins/manager.py", line 157, in load_plugin
    self._load()
  File "/home/dyens/.cache/pypoetry/virtualenvs/ttt-LUnx8CLc-py3.7/lib64/python3.7/site-packages/flake8/plugins/manager.py", line 134, in _load
    self._plugin = self.entry_point.load()
  File "/home/dyens/.cache/pypoetry/virtualenvs/ttt-LUnx8CLc-py3.7/lib64/python3.7/site-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/dyens/.cache/pypoetry/virtualenvs/ttt-LUnx8CLc-py3.7/lib64/python3.7/site-packages/flake8_isort.py", line 3, in <module>
    from isort import SortImports
ImportError: cannot import name 'SortImports' from 'isort' (/home/dyens/.cache/pypoetry/virtualenvs/ttt-LUnx8CLc-py3.7/lib64/python3.7/site-packages/isort/__init__.py)

```

### flake8 information

`flake8 --bug-report` does not work on the same reason:

```
> poetry run flake8 --bug-report
ERROR:flake8.plugins.manager:cannot import name 'SortImports' from 'isort' (/home/dyens/.cache/pypoetry/virtualenvs/ttt-LUnx8CLc-py3.7/lib64/python3.7/site-packages/isort/__init__.py)
]
...
```

### pip information

In my test environment i have installed only `wemake-python-styleguide` and it deps:

```
> poetry run pip freeze
astor==0.8.1
attrs==19.3.0
bandit==1.6.2
darglint==1.5.1
docutils==0.16
eradicate==1.0
flake8==3.8.3
flake8-bandit==2.1.2
flake8-broken-line==0.2.1
flake8-bugbear==19.8.0
flake8-commas==2.0.0
flake8-comprehensions==3.2.3
flake8-debugger==3.2.1
flake8-docstrings==1.5.0
flake8-eradicate==0.3.0
flake8-isort==2.9.1
flake8-polyfill==1.0.2
flake8-quotes==2.1.2
flake8-rst-docstrings==0.0.12
flake8-string-format==0.2.3
gitdb==4.0.5
GitPython==3.1.7
importlib-metadata==1.7.0
isort==5.1.1
mccabe==0.6.1
more-itertools==8.4.0
packaging==20.4
pbr==5.4.5
pep8-naming==0.9.1
pluggy==0.13.1
py==1.9.0
pycodestyle==2.6.0
pydocstyle==5.0.2
pyflakes==2.2.0
Pygments==2.6.1
pyparsing==2.4.7
pytest==5.4.3
PyYAML==5.3.1
restructuredtext-lint==1.3.1
six==1.15.0
smmap==3.0.4
snowballstemmer==2.0.0
stevedore==3.1.0
testfixtures==6.14.1
typing-extensions==3.7.4.2
wcwidth==0.2.5
wemake-python-styleguide==0.14.0
zipp==3.1.0
```

**Comment by nikiforniko** [comment]
Hi, look at my same issue #1510
