### ISSUE TITLE
annotation_node.slice.value,  # type: ignore AttributeError: 'Tuple' object has no attribute 'value'

### ISSUE THREAD

**Issue by tahirjalilov** [wemake-services/wemake-python-styleguide#1797]
# Bug report

## What's wrong

Traceback (most recent call last):
  File "/home/work_pc/Projects/test_project/venv/lib/python3.9/site-packages/wemake_python_styleguide/checker.py", line 154, in run
    visitor.run()
  File "/home/work_pc/Projects/test_project/venv/lib/python3.9/site-packages/wemake_python_styleguide/visitors/base.py", line 191, in run
    self.visit(self.tree)
  File "/home/work_pc/Projects/test_project/venv/lib/python3.9/site-packages/wemake_python_styleguide/visitors/base.py", line 186, in visit
    return route_visit(self, tree)
  File "/home/work_pc/Projects/test_project/venv/lib/python3.9/site-packages/wemake_python_styleguide/compat/routing.py", line 36, in route_visit
    return getattr(
  File "/usr/lib/python3.9/ast.py", line 415, in generic_visit
    self.visit(item)
  File "/home/work_pc/Projects/test_project/venv/lib/python3.9/site-packages/wemake_python_styleguide/visitors/base.py", line 186, in visit
    return route_visit(self, tree)
  File "/home/work_pc/Projects/test_project/venv/lib/python3.9/site-packages/wemake_python_styleguide/compat/routing.py", line 36, in route_visit
    return getattr(
  File "/home/work_pc/Projects/test_project/venv/lib/python3.9/site-packages/wemake_python_styleguide/visitors/ast/complexity/annotations.py", line 34, in visit_any_function
    self._check_function_annotations_complexity(node)
  File "/home/work_pc/Projects/test_project/venv/lib/python3.9/site-packages/wemake_python_styleguide/visitors/ast/complexity/annotations.py", line 58, in _check_function_annotations_complexity
    self._check_annotations_complexity(node, annotations)
  File "/home/work_pc/Projects/test_project/venv/lib/python3.9/site-packages/wemake_python_styleguide/visitors/ast/complexity/annotations.py", line 67, in _check_annotations_complexity
    complexity = get_annotation_compexity(annotation)
  File "/home/work_pc/Projects/test_project/venv/lib/python3.9/site-packages/wemake_python_styleguide/logic/complexity/annotations.py", line 36, in get_annotation_compexity
    annotation_node.slice.value,  # type: ignore
AttributeError: 'Tuple' object has no attribute 'value'

## System information

Operating System: Arch Linux
KDE Plasma Version: 5.20.4
KDE Frameworks Version: 5.77.0
Qt Version: 5.15.2
Kernel Version: 5.9.14-arch1-1
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-4770K CPU @ 3.50GHz
Memory: 15.6 GiB of RAM
Graphics Processor: GeForce GTX 460 SE/PCIe/SSE2

### flake8 information

{
  "dependencies": [],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.9.1",
    "system": "Linux"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "flake8-bandit",
      "version": "2.1.2"
    },
    {
      "is_local": false,
      "plugin": "flake8-broken-line",
      "version": "0.2.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-bugbear",
      "version": "19.8.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-comprehensions",
      "version": "3.3.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-darglint",
      "version": "1.5.8"
    },
    {
      "is_local": false,
      "plugin": "flake8-debugger",
      "version": "3.2.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-docstrings",
      "version": "1.5.0, pydocstyle: 5.1.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-eradicate",
      "version": "0.3.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-string-format",
      "version": "0.2.3"
    },
    {
      "is_local": false,
      "plugin": "flake8_commas",
      "version": "2.0.0"
    },
    {
      "is_local": false,
      "plugin": "flake8_isort",
      "version": "3.0.1"
    },
    {
      "is_local": false,
      "plugin": "flake8_quotes",
      "version": "2.1.2"
    },
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "naming",
      "version": "0.9.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.6.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.2.0"
    },
    {
      "is_local": false,
      "plugin": "rst-docstrings",
      "version": "0.0.12"
    },
    {
      "is_local": false,
      "plugin": "wemake_python_styleguide",
      "version": "0.14.1"
    }
  ],
  "version": "3.8.4"
}

### pip information

astor==0.8.1
attrs==20.3.0
bandit==1.7.0
certifi==2020.12.5
chardet==4.0.0
darglint==1.5.8
docutils==0.16
eradicate==1.0
flake8==3.8.4
flake8-bandit==2.1.2
flake8-broken-line==0.2.1
flake8-bugbear==19.8.0
flake8-commas==2.0.0
flake8-comprehensions==3.3.1
flake8-debugger==3.2.1
flake8-docstrings==1.5.0
flake8-eradicate==0.3.0
flake8-isort==3.0.1
flake8-polyfill==1.0.2
flake8-quotes==2.1.2
flake8-rst-docstrings==0.0.12
flake8-string-format==0.2.3
gitdb==4.0.5
GitPython==3.1.11
idna==2.10
isort==4.3.21
mccabe==0.6.1
pbr==5.5.1
pep8-naming==0.9.1
pycodestyle==2.6.0
pydocstyle==5.1.1
pyflakes==2.2.0
Pygments==2.7.3
PyYAML==5.3.1
requests==2.25.1
restructuredtext-lint==1.3.2
six==1.15.0
smmap==3.0.4
snowballstemmer==2.0.0
stevedore==3.3.0
testfixtures==6.17.0
toml==0.10.2
typing-extensions==3.7.4.3
urllib3==1.26.2
wemake-python-styleguide==0.14.1
xmltodict==0.12.0

**Comment by sobolevn** [comment]
Thanks! This is already fixed in `master`.
Python 3.9 support will land in `0.15`
