### ISSUE TITLE
Forbid to `raise` exception from itself

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#2133]
# Rule request

We need to forbid code like `raise exc from exc`, because it does not make much sense and works the same way:

```python
>>> e = Exception('m')
>>> raise e
Traceback (most recent call last):
  File "ex.py", line 1, in <module>
    e = Exception("m"); raise e
Exception: m
```

And with `from`:

```python
>>> e = Exception('m')
>>> raise e from e
Traceback (most recent call last):
  File "ex.py", line 1, in <module>
    e = Exception("m"); raise e
Exception: m
```

We need to explicitly test two cases:
1. New `raise`
2. Re-raising inside `except`

**Comment by shruthi223** [comment]
Hi! Could you please assign me this? Im new and would like to know more!

**Comment by sobolevn** [comment]
Hi! @shruthi223 thanks a lot! Take a look at https://github.com/wemake-services/wemake-python-styleguide/blob/master/CONTRIBUTING.md

**Comment by singhaditya28** [comment]
Hi, I am an aspiring Hacktoberfest newbie. Can I take on this? and is this eligible for hacktoberfest ?

**Comment by sobolevn** [comment]
@singhaditya28 yes, sure! Thank you!
