### ISSUE TITLE
ValueError: <ast.If object at 0x10e922d40> is not in list

### ISSUE THREAD

**Issue by Denis-Alexeev** [wemake-services/wemake-python-styleguide#2263]
### What's wrong

I get  0:   1 WPS000 Internal error happened, see log. Please, take some time to report it

Minimum reporducible example:
```python
def func():
    try:
        1/0
    except:
        pass
    else:
        if True:
            return True
```

```
Traceback (most recent call last):
  File "/.../venv/lib/python3.10/site-packages/wemake_python_styleguide/checker.py", line 154, in run
    visitor.run()
  File "/.../venv/lib/python3.10/site-packages/wemake_python_styleguide/visitors/base.py", line 191, in run
    self.visit(self.tree)
  File "/.../venv/lib/python3.10/site-packages/wemake_python_styleguide/visitors/base.py", line 186, in visit
    return route_visit(self, tree)
  File "/.../venv/lib/python3.10/site-packages/wemake_python_styleguide/compat/routing.py", line 36, in route_visit
    return getattr(
  File "/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ast.py", line 418, in generic_visit
    self.visit(item)
  File "/...venv/lib/python3.10/site-packages/wemake_python_styleguide/visitors/base.py", line 186, in visit
    return route_visit(self, tree)
  File "/.../venv/lib/python3.10/site-packages/wemake_python_styleguide/compat/routing.py", line 36, in route_visit
    return getattr(
  File "/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ast.py", line 418, in generic_visit
    self.visit(item)
  File "/.../venv/lib/python3.10/site-packages/wemake_python_styleguide/visitors/base.py", line 186, in visit
    return route_visit(self, tree)
  File "/.../venv/lib/python3.10/site-packages/wemake_python_styleguide/compat/routing.py", line 36, in route_visit
    return getattr(
  File "/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ast.py", line 418, in generic_visit
    self.visit(item)
  File "/.../venv/lib/python3.10/site-packages/wemake_python_styleguide/visitors/base.py", line 186, in visit
    return route_visit(self, tree)
  File "/.../venv/lib/python3.10/site-packages/wemake_python_styleguide/compat/routing.py", line 36, in route_visit
    return getattr(
  File "/.../venv/lib/python3.10/site-packages/wemake_python_styleguide/visitors/ast/conditions.py", line 77, in visit_any_if
    self._check_simplifiable_returning_if(node)
  File "/.../venv/lib/python3.10/site-packages/wemake_python_styleguide/visitors/ast/conditions.py", line 115, in _check_simplifiable_returning_if
    next_index_in_parent = body.index(node) + 1
ValueError: <ast.If object at 0x10e922d40> is not in list
```

Also it is reproducible in python 3.9

### How it should be

Internal error shouldn't be

### Flake8 version and plugins

{
  "dependencies": [],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.10.0",
    "system": "Darwin"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "flake8-bandit",
      "version": "2.1.2"
    },
    {
      "is_local": false,
      "plugin": "flake8-broken-line",
      "version": "0.3.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-bugbear",
      "version": "21.9.2"
    },
    {
      "is_local": false,
      "plugin": "flake8-comprehensions",
      "version": "3.7.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-darglint",
      "version": "1.8.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-debugger",
      "version": "4.0.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-docstrings",
      "version": "1.6.0, pydocstyle: 6.1.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-eradicate",
      "version": "1.2.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-string-format",
      "version": "0.3.0"
    },
    {
      "is_local": false,
      "plugin": "flake8_commas",
      "version": "2.1.0"
    },
    {
      "is_local": false,
      "plugin": "flake8_isort",
      "version": "4.1.1"
    },
    {
      "is_local": false,
      "plugin": "flake8_quotes",
      "version": "3.3.1"
    },
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "naming",
      "version": "0.11.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.7.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.3.1"
    },
    {
      "is_local": false,
      "plugin": "rst-docstrings",
      "version": "0.2.3"
    },
    {
      "is_local": false,
      "plugin": "wemake_python_styleguide",
      "version": "0.15.3"
    }
  ],
  "version": "3.9.2"
}

### pip information

pip 21.3.1 from /.../venv/lib/python3.10/site-packages/pip (python 3.10)
astor==0.8.1
attrs==21.2.0
bandit==1.7.1
darglint==1.8.1
docutils==0.18
eradicate==2.0.0
flake8==3.9.2
flake8-bandit==2.1.2
flake8-broken-line==0.3.0
flake8-bugbear==21.9.2
flake8-commas==2.1.0
flake8-comprehensions==3.7.0
flake8-debugger==4.0.0
flake8-docstrings==1.6.0
flake8-eradicate==1.2.0
flake8-isort==4.1.1
flake8-polyfill==1.0.2
flake8-quotes==3.3.1
flake8-rst-docstrings==0.2.3
flake8-string-format==0.3.0
gitdb==4.0.9
GitPython==3.1.24
isort==5.10.1
mccabe==0.6.1
pbr==5.8.0
pep8-naming==0.11.1
pycodestyle==2.7.0
pydocstyle==6.1.1
pyflakes==2.3.1
Pygments==2.10.0
PyYAML==6.0
restructuredtext-lint==1.3.2
six==1.16.0
smmap==5.0.0
snowballstemmer==2.2.0
stevedore==3.5.0
testfixtures==6.18.3
typing-extensions==3.10.0.2
wemake-python-styleguide==0.15.3

### OS information

MacOS BigSur

**Comment by Denis-Alexeev** [comment]
> Can you please try `master` version?

Yep. It does not happen if lib is installed as
`pip install git+https://github.com/wemake-services/wemake-python-styleguide.git@master`
I assume it can be closed then.

**Comment by sobolevn** [comment]
Thanks!
