### ISSUE TITLE
Broken GitHub Actions

### ISSUE THREAD

**Issue by SweetVishnya** [wemake-services/wemake-python-styleguide#2369]
### What's wrong

Hi!

I am using your GitHub Actions plugin:

```
    - name: Python code style linter
      uses: wemake-services/wemake-python-styleguide@0.16.0
```

And it seems to be broken:

```
Using reporter: terminal
Linting path: .
flake8 --version:
4.0.1 (flake8-bandit: 2.1.2, flake8-broken-line: 0.4.0, flake8-bugbear:
21.11.29, flake8-comprehensions: 3.8.0, flake8-darglint: 1.8.1,
flake8-debugger: 4.0.0, flake8-docstrings: 1.6.0, pydocstyle: 6.1.1,
flake8-eradicate: 1.2.0, flake8-string-format: 0.3.0, flake8_commas: 2.1.0,
flake8_isort: 4.1.1, flake8_quotes: 3.3.1, mccabe: 0.6.1, naming: 0.12.1,
pycodestyle: 2.8.0, pyflakes: 2.4.0, rst-docstrings: 0.2.5,
wemake_python_styleguide: 0.16.0) CPython 3.9.9 on Linux
=================================

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.9/site-packages/flake8/checker.py", line 687, in _run_checks
    return checker.run_checks()
  File "/usr/local/lib/python3.9/site-packages/flake8/checker.py", line 597, in run_checks
    self.run_ast_checks()
  File "/usr/local/lib/python3.9/site-packages/flake8/checker.py", line 500, in run_ast_checks
    for (line_number, offset, text, _) in runner:
  File "/usr/local/lib/python3.9/site-packages/flake8_bandit.py", line 85, in run
    for warn in self._check_source():
  File "/usr/local/lib/python3.9/site-packages/flake8_bandit.py", line 59, in _check_source
    bnv = BanditNodeVisitor(
TypeError: __init__() missing 1 required positional argument: 'metrics'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/usr/local/lib/python3.9/site-packages/flake8/main/application.py", line 375, in run
    self._run(argv)
  File "/usr/local/lib/python3.9/site-packages/flake8/main/application.py", line 364, in _run
    self.run_checks()
  File "/usr/local/lib/python3.9/site-packages/flake8/main/application.py", line 271, in run_checks
    self.file_checker_manager.run()
  File "/usr/local/lib/python3.9/site-packages/flake8/checker.py", line 309, in run
    self.run_parallel()
  File "/usr/local/lib/python3.9/site-packages/flake8/checker.py", line 275, in run_parallel
    for ret in pool_map:
  File "/usr/local/lib/python3.9/multiprocessing/pool.py", line 448, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/usr/local/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
TypeError: __init__() missing 1 required positional argument: 'metrics'
```

### How it should be

It should work in GitHub CI

### Flake8 version and plugins

```
flake8 --version:
4.0.1 (flake8-bandit: 2.1.2, flake8-broken-line: 0.4.0, flake8-bugbear:
21.11.29, flake8-comprehensions: 3.8.0, flake8-darglint: 1.8.1,
flake8-debugger: 4.0.0, flake8-docstrings: 1.6.0, pydocstyle: 6.1.1,
flake8-eradicate: 1.2.0, flake8-string-format: 0.3.0, flake8_commas: 2.1.0,
flake8_isort: 4.1.1, flake8_quotes: 3.3.1, mccabe: 0.6.1, naming: 0.12.1,
pycodestyle: 2.8.0, pyflakes: 2.4.0, rst-docstrings: 0.2.5,
wemake_python_styleguide: 0.16.0) CPython 3.9.9 on Linux
```

### pip information

```
flake8 --version:
4.0.1 (flake8-bandit: 2.1.2, flake8-broken-line: 0.4.0, flake8-bugbear:
21.11.29, flake8-comprehensions: 3.8.0, flake8-darglint: 1.8.1,
flake8-debugger: 4.0.0, flake8-docstrings: 1.6.0, pydocstyle: 6.1.1,
flake8-eradicate: 1.2.0, flake8-string-format: 0.3.0, flake8_commas: 2.1.0,
flake8_isort: 4.1.1, flake8_quotes: 3.3.1, mccabe: 0.6.1, naming: 0.12.1,
pycodestyle: 2.8.0, pyflakes: 2.4.0, rst-docstrings: 0.2.5,
wemake_python_styleguide: 0.16.0) CPython 3.9.9 on Linux
```

### OS information

GitHub Actions

**Comment by sobolevn** [comment]
Thanks for the report.

See https://github.com/wemake-services/wemake-python-styleguide/pull/2368 for the solution.

**Comment by SweetVishnya** [comment]
And how can I use latest master in GitHub Actions?

**Comment by sobolevn** [comment]
```
    - name: Python code style linter
      uses: wemake-services/wemake-python-styleguide@master
```

🙂 

I am releasing `0.16.1` right now.
