### ISSUE TITLE
bandit==1.7.4 wps==0.15.3 TypeError: __init__() missing 1 required positional argument: 'metrics'

### ISSUE THREAD

**Issue by bryzgaloff** [wemake-services/wemake-python-styleguide#2398]
### What's wrong

When running a Github Action for `wemake-services/wemake-python-styleguide@0.15.3`, an error occurs:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/pool.py", line 1[25](https://github.com/cloudthread/core-data-platform-airflow-workflows/runs/6055184012?check_suite_focus=true#step:4:25), in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.9/site-packages/flake8/checker.py", line 676, in _run_checks
    return checker.run_checks()
  File "/usr/local/lib/python3.9/site-packages/flake8/checker.py", line 589, in run_checks
    self.run_ast_checks()
  File "/usr/local/lib/python3.9/site-packages/flake8/checker.py", line 494, in run_ast_checks
    for (line_number, offset, text, _) in runner:
  File "/usr/local/lib/python3.9/site-packages/flake8_bandit.py", line 85, in run
    for warn in self._check_source():
  File "/usr/local/lib/python3.9/site-packages/flake8_bandit.py", line 59, in _check_source
    bnv = BanditNodeVisitor(
TypeError: __init__() missing 1 required positional argument: 'metrics'
```

### How it should be

The reason in bandit latest version being installed: `bandit==1.7.4`. When installing `bandint==1.7.2` everything works fine.

### Flake8 version and plugins

```
{
  "dependencies": [],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.8.10",
    "system": "Linux"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "flake8-bandit",
      "version": "2.1.2"
    },
    {
      "is_local": false,
      "plugin": "flake8-broken-line",
      "version": "0.3.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-bugbear",
      "version": "21.11.29"
    },
    {
      "is_local": false,
      "plugin": "flake8-comprehensions",
      "version": "3.8.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-darglint",
      "version": "1.8.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-debugger",
      "version": "4.0.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-docstrings",
      "version": "1.6.0, pydocstyle: 6.1.1"
    },
    {
      "is_local": false,
      "plugin": "flake8-eradicate",
      "version": "1.2.0"
    },
    {
      "is_local": false,
      "plugin": "flake8-string-format",
      "version": "0.3.0"
    },
    {
      "is_local": false,
      "plugin": "flake8_commas",
      "version": "2.1.0"
    },
    {
      "is_local": false,
      "plugin": "flake8_isort",
      "version": "4.1.1"
    },
    {
      "is_local": false,
      "plugin": "flake8_quotes",
      "version": "3.3.1"
    },
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "naming",
      "version": "0.11.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.8.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.3.1"
    },
    {
      "is_local": false,
      "plugin": "rst-docstrings",
      "version": "0.2.5"
    },
    {
      "is_local": false,
      "plugin": "wemake_python_styleguide",
      "version": "0.15.3"
    }
  ],
  "version": "3.9.2"
}
```

### pip information

pip 20.0.2 from /tmp/wps-fail-venv/lib/python3.8/site-packages/pip (python 3.8)
astor==0.8.1
attrs==21.4.0
bandit==1.7.4
darglint==1.8.1
docutils==0.18.1
eradicate==2.1.0
flake8==3.9.2
flake8-bandit==2.1.2
flake8-broken-line==0.3.0
flake8-bugbear==21.11.29
flake8-commas==2.1.0
flake8-comprehensions==3.8.0
flake8-debugger==4.0.0
flake8-docstrings==1.6.0
flake8-eradicate==1.2.0
flake8-isort==4.1.1
flake8-polyfill==1.0.2
flake8-quotes==3.3.1
flake8-rst-docstrings==0.2.5
flake8-string-format==0.3.0
gitdb==4.0.9
GitPython==3.1.27
isort==5.10.1
mccabe==0.6.1
pbr==5.8.1
pep8-naming==0.11.1
pycodestyle==2.8.0
pydocstyle==6.1.1
pyflakes==2.3.1
Pygments==2.11.2
PyYAML==6.0
restructuredtext-lint==1.4.0
six==1.16.0
smmap==5.0.0
snowballstemmer==2.2.0
stevedore==3.5.0
testfixtures==6.18.5
typing-extensions==3.10.0.2
wemake-python-styleguide==0.15.3

### OS information

Reproducible on Ubuntu 20.04.3 LTS and in Github Actions

**Comment by sobolevn** [comment]
Yes, this is a known bug. Please, update WPS, or `flake8-bandit`

**Comment by bryzgaloff** [comment]
How to do it in case of Github Action? Is it completely unusable for version 0.15.3 now?

**Comment by sobolevn** [comment]
Yes, looks like it. This is a problem on `flake8-bandit` / `bandit`'s side.
