### ISSUE TITLE
`poetry run flake8` raises an exception

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#387]
# Bug report

## What's wrong

```
» poetry run flake8
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/Users/sobolev/Desktop/test_project/.venv/lib/python3.6/site-packages/flake8/checker.py", line 451, in run_check
    return plugin["plugin"](**arguments)
  File "/Users/sobolev/Desktop/test_project/.venv/lib/python3.6/site-packages/flake8/plugins/pyflakes.py", line 100, in __init__
    tree, filename, withDoctest=with_doctest
  File "/Users/sobolev/Desktop/test_project/.venv/lib/python3.6/site-packages/pyflakes/checker.py", line 498, in __init__
    self.runDeferred(self._deferredFunctions)
  File "/Users/sobolev/Desktop/test_project/.venv/lib/python3.6/site-packages/pyflakes/checker.py", line 535, in runDeferred
    handler()
  File "/Users/sobolev/Desktop/test_project/.venv/lib/python3.6/site-packages/pyflakes/checker.py", line 1228, in runFunction
    self.handleNode(stmt, node)
  File "/Users/sobolev/Desktop/test_project/.venv/lib/python3.6/site-packages/pyflakes/checker.py", line 871, in handleNode
    handler(node)
  File "/Users/sobolev/Desktop/test_project/.venv/lib/python3.6/site-packages/pyflakes/checker.py", line 1369, in TRY
    self.handleChildren(node, omit='body')
  File "/Users/sobolev/Desktop/test_project/.venv/lib/python3.6/site-packages/pyflakes/checker.py", line 824, in handleChildren
    self.handleNode(node, tree)
  File "/Users/sobolev/Desktop/test_project/.venv/lib/python3.6/site-packages/pyflakes/checker.py", line 871, in handleNode
    handler(node)
  File "/Users/sobolev/Desktop/test_project/.venv/lib/python3.6/site-packages/pyflakes/checker.py", line 824, in handleChildren
    self.handleNode(node, tree)
  File "/Users/sobolev/Desktop/test_project/.venv/lib/python3.6/site-packages/pyflakes/checker.py", line 871, in handleNode
    handler(node)
  File "/Users/sobolev/Desktop/test_project/.venv/lib/python3.6/site-packages/pyflakes/checker.py", line 1306, in TUPLE
    self.handleChildren(node)
  File "/Users/sobolev/Desktop/test_project/.venv/lib/python3.6/site-packages/pyflakes/checker.py", line 824, in handleChildren
    self.handleNode(node, tree)
  File "/Users/sobolev/Desktop/test_project/.venv/lib/python3.6/site-packages/pyflakes/checker.py", line 871, in handleNode
    handler(node)
  File "/Users/sobolev/Desktop/test_project/.venv/lib/python3.6/site-packages/pyflakes/checker.py", line 1102, in NAME
    self.handleNodeStore(node)
  File "/Users/sobolev/Desktop/test_project/.venv/lib/python3.6/site-packages/pyflakes/checker.py", line 790, in handleNodeStore
    self.addBinding(node, binding)
  File "/Users/sobolev/Desktop/test_project/.venv/lib/python3.6/site-packages/pyflakes/checker.py", line 668, in addBinding
    if existing and not self.differentForks(node, existing.source):
  File "/Users/sobolev/Desktop/test_project/.venv/lib/python3.6/site-packages/pyflakes/checker.py", line 651, in differentForks
    self.descendantOf(rnode, items, ancestor):
  File "/Users/sobolev/Desktop/test_project/.venv/lib/python3.6/site-packages/pyflakes/checker.py", line 640, in descendantOf
    if self.getCommonAncestor(node, a, stop):
  File "/Users/sobolev/Desktop/test_project/.venv/lib/python3.6/site-packages/pyflakes/checker.py", line 632, in getCommonAncestor
    if (lnode.depth > rnode.depth):
AttributeError: 'Assign' object has no attribute 'depth'
```

## How is that should be

It should not raise any errors.

## System information

Reproduction steps:
1. `cookiecutter /Users/sobolev/Documents/github/wemake-django-template`
2. `poetry install`
3. `poetry run flake8`

**Comment by sobolevn** [comment]
It works for all files in the repo. Things I have tried:
1. `flake8 server`
2. `flake8 tests`
3. `flake8 manage.py`
4. `flake8 docs`
5. `flake8 **/*.py`

So, this is just unexplainable.

**Comment by sobolevn** [comment]
This is not related to our project at all.
